Bitsquare Developer Guide
=========================
Chris Beams <chris@beams.io>
:toc:

Introduction
------------

TODO

Build from source
-----------------

This section of the guide will walk you through the process of building Bitsquare from source.

NOTE: For most users, building from source is not necessary. See the https://github.com/bitsquare/bitsquare/releases[releases page], where you'll find installers for Windows, Linux and Mac OS X.


=== For the impatient

What follows is explained in detail in the sections below, but for those who know their way around Java, git and Gradle, here are the instructions in a nutshell:

    $ javac -version
    javac 1.8.0_20       # must be 1.8.0_20 or better

    $ git clone https://github.com/bitsquare/bitsquare.git
    $ cd bitsquare
    $ ./gradlew build    # (on *nix)
       --- or ---
    $ gradlew build      # (on Windows)

When the build completes, you will find executables and installers specific to your platform in the `build/distributions/` directory.


=== Prerequisites

The only prerequisite for building Bitsquare is installing the Java Development Kit (JDK), version 8u20 or better.

To check the version of Java you currently have installed:

    $ javac -version
    javac 1.8.0_20

If `javac` is not found, or your version is anything less than `1.8.0_20`, then you'll need to http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[download and install the latest JDK] for your platform.

TIP: Here are http://www.webupd8.org/2014/03/how-to-install-oracle-java-8-in-debian.html[instructions] for installing the JDK via `apt` on Debian or Ubuntu systems.


=== Steps

==== 1. Get the source

The preferred approach is to clone the Bitsquare repository using http://www.git-scm.com/[git]:

    git clone https://github.com/bitsquare/bitsquare.git

However, if you're not familiar with git or it is otherwise inconvenient to use, you can also download and extract a zip file of the latest sources at https://github.com/bitsquare/bitsquare/archive/master.zip.


==== 2. Build

Bitsquare uses http://www.gradle.org/[Gradle], and the http://www.gradle.org/docs/current/userguide/gradle_wrapper.html[Gradle wrapper] as a build system. This means you don't need to download or do anything other than run the following command within the `bitsquare` directory.

    ./gradlew build

NOTE: on Windows, leave out the `./` and simply run `gradlew build`.


==== 3. Run

When the build completes, you'll find executables and installers in the `build/distributions` directory.


=== Troubleshooting

If the instructions above don't work for you, please https://github.com/bitsquare/bitsquare/issues/new?labels=%5Bbuild%5D[raise an issue]. Thanks!
