Bitsquare User Guide
====================
:revnumber: {project-version}
:download-baseurl: https://github.com/bitsquare/bitsquare/releases/download/v{project-version}/bitsquare-{project-version}
:devguide-url: http://bitsquare.io/docs/{project-version}/devguide.html
:toc:
:numbered:

Introduction
------------

Welcome, and thanks for your interest in Bitsquare. 

What is Bitsquare?
~~~~~~~~~~~~~~~~~~

Bitsquare is a cross-platform desktop application that allows users to trade 'fiat money' (dollars, euros, etc) for bitcoin without relying on centralized exchanges such as Coinbase, Bitstamp or (the former) Mt. Gox.

By running Bitsquare on their individual computers, users work together to form a peer-to-peer network. Through the Bitsquare interface, users broadcast offers to buy and sell bitcoin on that network. The process of offering and accepting these trades results in a fully functioning, yet totally decentralized marketplace.

Why Bitsquare?
~~~~~~~~~~~~~~

TODO

Who should use Bitsquare?
~~~~~~~~~~~~~~~~~~~~~~~~~

TODO

About this guide
~~~~~~~~~~~~~~~~

This document is designed to provide users with clear and complete instructions on how to use Bitsquare to buy and sell bitcoin. It does not address technical details or provide instructions for developers or arbitrators. For more information on these topics, see <<further-reading>>.

If you're new to Bitsquare, we recommend you begin by looking over the <<use-cases>> section to get a clear picture of what Bitsquare can do. If you like what you see, then follow the steps in the <<getting-started>> section. From there, you can move on to the <<how-to>> section, where you'll find specific instructions how to <<set-up-account>> <<place-offer-to-buy>> and <<take-offer-to-buy>> guides that will walk you through the process of placing an offer to 

The source for this guide can be found at TODO.

Should you find any errors in the guide or have suggestions for improvement, please https://github.com/bitsquare/bitsquare/issues/new?labels=%5Bdocs%5D[raise an issue] or mailto:team@bitsquare.io?subject=User+Guide+feedback[send us an email].

[[further-reading]]
Further reading
~~~~~~~~~~~~~~~

You can read about all of this and more in the http://bitsquare.io/images/overview.png[overview], https://docs.google.com/document/d/1d3EiWZdaM89-P6MVhS53unXv2-pDpSFsN3W4kCGXKgY/edit#[whitepaper], https://docs.google.com/document/d/1LJCRFdtM2Jn2Oiv49qRXwBDG8HZD0Hiedy8tNjErHps/edit[arbitration] and https://docs.google.com/document/d/1sHwU7K7C8Nl-fS4Z6X88L-NVJ_WBiKnsSpYpYfyqUXA/edit[risk analysis] documents. Several https://docs.google.com/document/d/1d3EiWZdaM89-P6MVhS53unXv2-pDpSFsN3W4kCGXKgY/edit#[screencasts] are available as well.


TODO

[[getting-started]]
Getting Started
---------------

This is alpha software.

We recommend that you follow the steps in <<getting-started>>


Download and install Bitsquare
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Mac OS X
^^^^^^^^

Download the Bitsquare {download-baseurl}.dmg[.dmg image]. Open it, and copy Bitsquare to your `/Applications` folder.

TODO: screenshot

Linux
^^^^^

Linux users on Debian- or Ubuntu-based distributions can download the Bitsquare {download-baseurl}.deb[.deb package] and install it using `dpkg`. Linux users on other distributions can {devguide-url}#build-from-source[build from source].

Windows
^^^^^^^

A Windows MSI installer will be https://github.com/bitsquare/bitsquare/issues/108[included in a future release]. Until then, Windows users can {devguide-url}#build-from-source[build from source].

Take a quick tour
~~~~~~~~~~~~~~~~~

At this point you can launch Bitsquare from your operating system's application menu. Take a look around the UI. You'll see that certain screens such as _Overview_, _Preferences_ and _Messages_ are not implemented yet. And you'll see that _Buy BTC_, _Sell BTC_, _Orders_, _Funds_ and _Account_ are. You'll see how to use each of these in the sections below.


[[use-cases]]
Use Cases
---------

Alice offers to buy, Bob takes her offer and sells
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Prepare
^^^^^^^

 1. <<delete-data-dirs>>—unless this is the first testing scenario.
 2. <<launch-alice>> and <<set-up-account>>, using "United States" in the 'Accepted Countries' and 'Location of Bank' fields.
 3. <<launch-bob>> and <<set-up-account>>, using "United States" in the 'Accepted Countries' and 'Location of Bank' fields.

'Alice': publish an offer to buy 1.0 bitcoin
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 1. <<publish-buy-offer>> with `1.00` as the 'Amount of Bitcoin to buy', `250.00` as 'Price per Bitcoin in USD' and `0.80` as the 'Minimum amount of Bitcoin'.
 2. <<review-open-offers>> and verify that Alice's offer to buy 1.0 BTC shows up as expected.

'Bob': take the offer and sell 0.8 bitcoin
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 1. <<review-open-offers>> and verify that Alice's offer to buy 1.0 BTC shows up as expected.
 2. <<take-buy-offer>> with `0.80` as 'Amount of bitcoin to sell'.
 3. <<review-open-offers>> and verify the 1 BTC order shows up as expected.

Wait for confirmation

In a terminal window, launch the 'Alice' instance of Bitsquare with the following command:


 - Set up account


How-To
------

[[set-up-account]]
Set up an account
~~~~~~~~~~~~~~~~~

TODO


Buy bitcoin
~~~~~~~~~~~

[[publish-buy-offer]]
Publish an offer to buy
^^^^^^^^^^^^^^^^^^^^^^^

TODO

[[take-sell-offer]]
Take an offer to sell
^^^^^^^^^^^^^^^^^^^^^

TODO


Sell bitcoin
~~~~~~~~~~~~

[[publish-sell-offer]]
Publish an offer to sell
^^^^^^^^^^^^^^^^^^^^^^^^

TODO

[[take-buy-offer]]
Take an offer to buy
^^^^^^^^^^^^^^^^^^^^

TODO


[[review-open-offers]]
Review open offers
~~~~~~~~~~~~~~~~~~

TODO

[[testing]]
[appendix]
Testing
-------

[[use-regtest]]
Use the bitcoin 'regtest' network
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Install Bitcoin Core
^^^^^^^^^^^^^^^^^^^^

Configure Bitcoin Core
^^^^^^^^^^^^^^^^^^^^^^

Use two instances of Bitsquare on the same machine
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Create a second copy of Bitsquare
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Assuming you have already gone through the steps to <<install-bitsquare>>, you can create a second copy for testing purposes by running the following command from a terminal window:

    cp -r /Applications/Bitsquare.app /Applications/Bitsquare2.app/

[[launch-alice]]
Launch the 'Alice' Bitsquare instance
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    /Applications/Bitsquare.app/Contents/MacOS/Bitsquare Alice

[[launch-bob]]
Launch the 'Bob' Bitsquare instance
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    /Applications/Bitsquare2.app/Contents/MacOS/Bitsquare Bob

[[delete-data-dirs]]
Delete 'Alice' and 'Bob' Bitsquare data directories
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    rm -rf ~/Library/Application\ Support/Bitsquare
    rm -rf ~/Library/Application\ Support/Bitsquare2
