Bitsquare User Guide
====================
:version:       {project-version}
:revnumber:     {version} (Alpha)
:repo-url:      https://github.com/bitsquare/bitsquare
:download-url:  {repo-url}/releases/download/v{version}
:devguide-url:  http://bitsquare.io/docs/{version}/devguide.html
:browse-url:    {repo-url}/blob/master
:toc:
:toc-placement!:
:numbered:

.Welcome!
**********************************************************************
If you're new to Bitsquare, we recommend you begin by reading the <<introduction>> and browsing the <<use-cases>> to get a clear picture of what Bitsquare is and what it can do. If you like what you see, then follow the steps in <<getting-started>>. From there, move on to the <<how-to>> section, where you'll find specific instructions on how to set up your account, place and take offers and more. Having trouble along the way? See the <<faq>>—but don't hesitate to {repo-url}#staying-in-touch[contact the team] if you get stuck.

Thanks for your interest, and we look forward to hearing from you!
**********************************************************************

NOTE: We're working our way toward a 1.0 release, but right now **Bitsquare is alpha-quality software**. This means that it should only be used on the bitcoin 'testnet' and 'regtest' networks. If you're not familiar with what that means, don't worry—instructions will be given along the way. Happy testing!

toc::[]

[[introduction]]
Introduction
------------

What is Bitsquare?
~~~~~~~~~~~~~~~~~~

Bitsquare is a cross-platform desktop application that allows users to trade 'fiat money' (dollars, euros, etc) for bitcoin without relying on centralized exchanges such as Coinbase, Bitstamp or (the former) Mt. Gox.

By running Bitsquare on their individual computers, users work together to form a peer-to-peer network. Through the Bitsquare interface, users broadcast offers to buy and sell bitcoin on that network. The process of offering and accepting these trades results in a fully functioning, yet totally decentralized marketplace.

Why Bitsquare?
~~~~~~~~~~~~~~

TODO

Who should use Bitsquare?
~~~~~~~~~~~~~~~~~~~~~~~~~

TODO

About this guide
~~~~~~~~~~~~~~~~

Purpose
^^^^^^^
This document is designed to provide Bitsquare users with clear and complete instructions on how to use Bitsquare to buy and sell bitcoin. It does not address technical details or provide instructions specific to Bitsquare developers or arbitrators. For more information on these and other topics, see <<additional-resources>>.

Conventions
^^^^^^^^^^^
TODO

Feedback
^^^^^^^^
Should you find any errors in the guide or have suggestions for improvement, please https://github.com/bitsquare/bitsquare/issues/new?labels=%5Bdocs%5D[raise an issue] or mailto:team@bitsquare.io?subject=User+Guide+feedback[send us an email].

Source
^^^^^^
This guide is authored in Asciidoc and the source can be found at {browse-url}/docs/userguide.adoc[docs/userguide.adoc] in the main Bitsquare repository. 

Copyright
^^^^^^^^^
TODO, but in the meantime, _all rights reserved_.


[[getting-started]]
Getting Started
---------------

Download and install Bitsquare
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Mac OS X
^^^^^^^^
Download the Bitsquare {download-url}/bitsquare-{version}.dmg[.dmg image]. Open it, and copy Bitsquare to your `/Applications` folder.

TODO: screenshot

Linux
^^^^^
Linux users on Debian- or Ubuntu-based distributions can download the Bitsquare {download-url}/bitsquare-{version}.deb[.deb package] and install it using `dpkg`. Linux users on other distributions can {devguide-url}#build-from-source[build from source].

Windows
^^^^^^^
A Windows MSI installer will be https://github.com/bitsquare/bitsquare/issues/108[included in a future release]. Until then, Windows users can {devguide-url}#build-from-source[build from source].

Take a quick tour
~~~~~~~~~~~~~~~~~

At this point you can launch Bitsquare from your operating system's application menu. Take a look around the UI. You'll see that certain screens such as _Overview_, _Preferences_ and _Messages_ are not implemented yet. And you'll see that _Buy BTC_, _Sell BTC_, _Orders_, _Funds_ and _Account_ are. You'll see how to use each of these in the sections below.


[[use-cases]]
Use Cases
---------

Alice places offer to buy, Bob takes it
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Prepare
^^^^^^^
 1. <<delete-data-dirs>>—unless this is the first testing scenario.
 2. <<launch-alice>> and <<set-up-account>>, using "United States" in the 'Accepted Countries' and 'Location of Bank' fields.
 3. <<launch-bob>> and <<set-up-account>>, using "United States" in the 'Accepted Countries' and 'Location of Bank' fields.

'Alice': place an offer to buy 1.0 bitcoin
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 1. <<place-buy-offer>> with `1.00` as the 'Amount of Bitcoin to buy', `250.00` as 'Price per Bitcoin in USD' and `0.80` as the 'Minimum amount of Bitcoin'.
 2. <<review-open-offers>> and verify that Alice's offer to buy 1.0 BTC shows up as expected.

'Bob': take the offer and sell 0.8 bitcoin
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 1. <<review-open-offers>> and verify that Alice's offer to buy 1.0 BTC shows up as expected.
 2. <<take-buy-offer>> with `0.80` as 'Amount of bitcoin to sell'.
 3. <<review-open-offers>> and verify the 1 BTC order shows up as expected.

Wait for confirmation

In a terminal window, launch the 'Alice' instance of Bitsquare with the following command:


 - Set up account


[[how-to]]
How-To
------

[[set-up-account]]
Set up an account
~~~~~~~~~~~~~~~~~

TODO


Buy bitcoin
~~~~~~~~~~~

There are two ways to buy bitcoin using Bitsquare: You can place your own offer to buy, or you can search TODO

[[place-buy-offer]]
Place an offer to buy
^^^^^^^^^^^^^^^^^^^^^
TODO

[[take-sell-offer]]
Take an offer to sell
^^^^^^^^^^^^^^^^^^^^^
TODO


Sell bitcoin
~~~~~~~~~~~~

[[place-sell-offer]]
Place an offer to sell
^^^^^^^^^^^^^^^^^^^^^^
TODO

[[take-buy-offer]]
Take an offer to buy
^^^^^^^^^^^^^^^^^^^^
TODO


[[review-open-offers]]
Review open offers
~~~~~~~~~~~~~~~~~~

TODO


[[additional-resources]]
[appendix]
Additional resources
--------------------

 - http://bitsquare.io/images/overview.png[Overview Infographic]
 - https://docs.google.com/document/d/1d3EiWZdaM89-P6MVhS53unXv2-pDpSFsN3W4kCGXKgY/edit#[Whitepaper]
 - https://docs.google.com/document/d/1LJCRFdtM2Jn2Oiv49qRXwBDG8HZD0Hiedy8tNjErHps/edit[Arbitration System]
 - https://docs.google.com/document/d/1sHwU7K7C8Nl-fS4Z6X88L-NVJ_WBiKnsSpYpYfyqUXA/edit[Risk Analysis]
 - https://docs.google.com/document/d/1d3EiWZdaM89-P6MVhS53unXv2-pDpSFsN3W4kCGXKgY/edit#[Screencasts]
 - {devguide-url}[Developer Guide]


[[testing]]
[appendix]
Testing
-------

[[use-regtest]]
Use the bitcoin 'regtest' network
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Install Bitcoin Core
^^^^^^^^^^^^^^^^^^^^
TODO

Configure Bitcoin Core
^^^^^^^^^^^^^^^^^^^^^^
TODO

Use two instances of Bitsquare on the same machine
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Create a second copy of Bitsquare
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Assuming you have already gone through the steps to <<install-bitsquare>>, you can create a second copy for testing purposes by running the following command from a terminal window:

    cp -r /Applications/Bitsquare.app /Applications/Bitsquare2.app/

[[launch-alice]]
Launch the 'Alice' Bitsquare instance
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    /Applications/Bitsquare.app/Contents/MacOS/Bitsquare Alice

[[launch-bob]]
Launch the 'Bob' Bitsquare instance
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    /Applications/Bitsquare2.app/Contents/MacOS/Bitsquare Bob

[[delete-data-dirs]]
Delete 'Alice' and 'Bob' Bitsquare data directories
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    rm -rf ~/Library/Application\ Support/Bitsquare
    rm -rf ~/Library/Application\ Support/Bitsquare2


[[faq]]
[appendix]
Frequently Asked Questions
--------------------------
[qanda]
I don't have any bitcoin. How can I get enough to pay the security deposit on my first trade?::
  TODO

Second question:: Second answer

